In [14]:
# 2차원 리스트
a = [[0] * 3 for i in range(3)]
print(a,"\n")
a[0][1] = 1
print(a, "\n")
print("*"*80)

print("2차원 리스트를 '행렬'로 나타내기 :","\n")
for i in a:
    
    print(i)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]] 

[[0, 1, 0], [0, 0, 0], [0, 0, 0]] 

********************************************************************************
2차원 리스트를 '행렬'로 나타내기 : 

[0, 1, 0]
[0, 0, 0]
[0, 0, 0]


In [6]:
b = np.array([[0, 0, 0],
            [0, 0, 0],
            [0, 0, 0]])
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
